version: '2'

services:
  docker-mariadb:
    image: mariadb:rc-focal
    volumes:
      - ./mariadb/dump/:/docker-entrypoint-initdb.d/
      - ./mariadb/data/:/var/lib/mysql
    restart: always
#    ports:
#      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: MvD2KHNcNrj5rW-4pNEL_PVKnLYx3
    container_name: mariadb_hesk
    networks:
      hesk:
          ipv4_address: 172.20.69.10

  docker-hesk:
    build: hesk/.
    restart: always
    volumes:
      - ./hesk/:/var/www/html/
    networks:
      hesk:
          ipv4_address: 172.20.69.101
##  command: "chmod 666 ./hesk_settings.inc.php && chmod 777 ./attachments && chmod 777 ./cache"

  docker-lb:
    build: ./nginx/.
    restart: always
    container_name: lb-hesk
    depends_on:
      - docker-hesk
    ports:
      - 8080:4000
      - 44300:4001
    networks:
      hesk:
          ipv4_address: 172.20.69.2

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      hesk:
          ipv4_address: 172.20.69.3

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana_storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always
    networks:
      hesk:
          ipv4_address: 172.20.69.4

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: always
    networks:
      hesk:
          ipv4_address: 172.20.69.5


  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8081:8080
    restart: always
    networks:
      hesk:
          ipv4_address: 172.20.69.6

networks:
  hesk:
    ipam:
      config:
        - subnet: 172.20.69.0/24
